deprecate example
ARMmbed/mbed-os-example-wifi pull request #206
Opened 2020-11-24 20:21 UTC by paul-szczepanek-arm

The netsocket example now includes the extra wifi elements so to cut down on duplication and maintenance this is being removed. Message links to the https://github.com/ARMmbed/mbed-os-example-sockets which is taking over.

2020-12-31 14:44 UTC, paul-szczepanek-arm commented
Wifi is now part of the sockets example

2021-01-04 14:07 UTC, pan- approved these changes
Looks good, have you checked in the documentation and website for references to this example ? 

I just found a reference at https://os.mbed.com/teams/ST/wiki/How-to-make-wifi-tests . 

@donatieng Are you happy with this deprecation notice or do you expect something else ? The netsocket example covers all aspects of this example now.

2021-01-11 09:36 UTC, 0xc0170 commented
> @donatieng Are you happy with this deprecation notice or do you expect something else ? The netsocket example covers all aspects of this example now.

I'll create a story to document how to deprecate Mbed OS component, we should have this available and followed.

2021-01-11 11:51 UTC, donatieng requested changes
@paul-szczepanek-arm Could you elaborate on the reason for deprecation, and maybe add a mention that the Socket examples have WiFi support? Plus maybe a warning icon? @0xc0170 would be worth using this example as a reference for deprecation.

2021-01-11 11:51 UTC, donatieng commented on README.md
> +## this example has been deprecated
This needs capitalisation

2021-01-11 12:13 UTC, donatieng approved these changes
Thanks Paul, LGTM
@0xc0170 are you happy with this as template?

2021-01-11 12:15 UTC, merged